/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './types/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Commonly used utility classes that might be dynamically generated
    'bg-brand-50',
    'bg-brand-100',
    'bg-brand-500',
    'bg-brand-600',
    'bg-brand-700',
    'text-brand-600',
    'text-brand-700',
    'hover:bg-brand-700',
    'hover:text-brand-700',
    'focus-visible:ring-brand-500',
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'text-gray-600',
    'text-gray-700',
    'text-gray-900',
    'border-gray-300',
    'hover:bg-gray-50',
    'rounded-lg',
    'rounded-xl',
    'shadow-lg',
    'px-4',
    'px-6',
    'px-8',
    'py-2',
    'py-12',
    'mb-4',
    'mb-6',
    'mb-8',
    'mt-8',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
    },
    extend: {
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}