name: Validate Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run production build
        run: npm run build
        
      - name: Check CSS generation
        run: node scripts/check-css-size.js
      
      - name: Start production server
        run: |
          npm run start &
          sleep 5
          
      - name: Test homepage renders
        run: |
          curl -f http://localhost:3000 || exit 1
          
      - name: Check for Tailwind classes
        run: |
          response=$(curl -s http://localhost:3000)
          if [[ ! "$response" == *"bg-white"* ]]; then
            echo "❌ Tailwind classes not found in HTML"
            exit 1
          fi
          echo "✅ Tailwind classes detected"
